# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: G:/vivado/MCU-5_stage_pipeline/MCU-5_stage_pipeline/5_stage_pipeline/DataPath_modules/design/data_mem_d_IP/data_mem_d_IP.xci
# IP: The module: 'data_mem_d_IP' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/vivado/MCU-5_stage_pipeline/MCU-5_stage_pipeline/5_stage_pipeline/DataPath_modules/design/data_mem_d_IP/data_mem_d_IP_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_mem_d_IP'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: G:/vivado/MCU-5_stage_pipeline/MCU-5_stage_pipeline/5_stage_pipeline/DataPath_modules/design/data_mem_d_IP/data_mem_d_IP.xci
# IP: The module: 'data_mem_d_IP' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/vivado/MCU-5_stage_pipeline/MCU-5_stage_pipeline/5_stage_pipeline/DataPath_modules/design/data_mem_d_IP/data_mem_d_IP_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_mem_d_IP'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
